FROM ubuntu:latest

#install python
RUN apt-get update
RUN apt-get install -y software-properties-common
RUN add-apt-repository ppa:deadsnakes/ppa
RUN apt-get update
RUN apt-get install -y python3.10
RUN ln -s /usr/bin/python3 /usr/bin/python
RUN apt-get install -y python3-pip
RUN apt install wget


#set the application working directory inside the container
WORKDIR /bdp2


# copies all the files in the current folder to working dir in container
ADD . /bdp2

# Create a Virtual environment
RUN pip install virtualenv
ENV VIRTUAL_ENV=/bdp2_venv
RUN virtualenv venv -p python3
ENV PATH="$VIRTUAL_ENV/bin/:$PATH"

# Install dependencies
RUN pip install -r requirements.txt
RUN python3 -m pip install spacy 
RUN python3 -m spacy download en_core_web_sm


# Install DVC
RUN cd /etc/apt/sources.list.d \
&& wget https://dvc.org/deb/dvc.list \
&& apt-get update \
&& apt-get install --yes dvc \
&& apt-get clean \
&& rm --recursive --force /var/lib/apt/lists/*

# Run the application
CMD ["dvc","repro"]
# RUN dvc pull
# RUN dvc repro